apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
data:
  config.env: QVBJX0tFWT10ZXN0
kind: Secret
metadata:
  name: config-env
  namespace: monitoring
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: singular
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      name.app.kubernetes: singular
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name.app.kubernetes: singular
    spec:
      containers:
      -   name: singular
          image: quay.io/rootfs/singular:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8000
            name: http
          resources: {}
          volumeMounts:
            - mountPath: /opt/config.env
              subPath: config.env
              name: dotenv
      restartPolicy: Always
      volumes:
        - name: dotenv
          secret:
            secretName: config-env
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name.app.kubernetes: singular
  name: singular
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8000
    targetPort: http
  selector:
    name.app.kubernetes: singular
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: prometheus
    name.app.kubernetes: singular
  name: prometheus-k8s
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: monitoring
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    name.app.kubernetes: singular
  name: singular
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: http
    relabelings:
    - action: replace
      regex: (.*)
      replacement: $1
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: instance
    scheme: http
  jobLabel: name.app.kubernetes
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      name.app.kubernetes: singular
