FROM python:latest

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
ADD singular.py /opt
ADD *.json /opt
# test it with
# podman run -ti -v `pwd`:/opt --net=host quay.io/rootfs/singular:latest
WORKDIR /opt
ENTRYPOINT [ "python3", "singular.py"]
