apiVersion: apps/v1
kind: Deployment
metadata:
  name: co2signal-producer
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      name.app.kubernetes: co2signal-producer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name.app.kubernetes: co2signal-producer
    spec:
      containers:
      -   name: co2signal-producer
          image: quay.io/sustainable_computing_io/co2signal_producer:latest
          imagePullPolicy: Always
          resources: {}
          volumeMounts:
            - mountPath: /opt/producer.env
              subPath: producer.env
              name: dotenv
      restartPolicy: Always
      volumes:
        - name: dotenv
          secret:
            secretName: co2signal-config